name: FlyCommand
version: '${project.version}'
main: me.widdleljk.flycommand.FlyCommand
commands:
  fly:
    description: "Be able to fly"
    usage: "/fly"
    permission: "flyvanish.fly"
    permission-message: "You don't have the required permissions!"
permissions:
  flyvanish.fly:
    default: op
    description: "able to fly"
  flyvanish.givefly:
    default: op
    description: "Able to give other people fly"