name: flyvanish
version: '${project.version}'
main: me.skycraftalfieedyvean.flyvanish.Flyvanish
commands:
  fly:
    description: "Be able to fly"
    usage: "/fly"
    permission: "flyvanish.fly"
    permission-message: "You don't have the required permissions!"
  vanish:
    description: "Vanishes you from the world!"
permissions:
  flyvanish.fly:
    default: op
    description: "able to fly"
  flyvanish.givefly:
    default: op
    description: "Able to give other people fly"
  flyvanish.vanish:
    default: op
    description: "Able to go invisible"